### PR TITLE
added badge and make CL responsive

### PR DESCRIPTION
**Pull request by TusharJade**
Screenshot (8)
Screenshot (7)

### CODE REVIEW

**Review by sumitch29 — APPROVED** [review]
Looks good

**Review by sakshi006 — APPROVED** [review]
Good to go.

**Review by rishichourasia — COMMENTED** [review]
looks good to me , just that code sample font looks little smaller , making it difficult to read , maybe increase that text size and see if that fits

**Comment by TusharJade** [comment]
Right bro, I will fix it now and merge it

**Comment by TusharJade** [comment]
> looks good to me , just that code sample font looks little smaller , making it difficult to read , maybe increase that text size and see if that fits

cant able to increase it, there is no option there for increasing size of that texts will go forward for now. After completing CL will look into it

**Pull request merged**
