### PR TITLE
Card

### PR DESCRIPTION
**Pull request by TusharJade**
### Added card component and updated installation

Screenshot (26)
Screenshot (25)

Screenshot (27)

Screenshot (28)

### CODE REVIEW

**Review by Asuraking1n — APPROVED** [review]
Look cool to me

**Review by harshitpaliwal95 — COMMENTED** [review]
Good to go

**Review by harshitpaliwal95 — COMMENTED** [review]
Try to use color variables everywhere

**Comment by harshitpaliwal95** [comment]
Ui looks great

**Comment by TusharJade** [comment]
> Try to use color variables everywhere

Yup, will convert all colors into variable.

**Pull request merged**
