### PR TITLE
Avtar badge

### PR DESCRIPTION
**Pull request by TusharJade**
First pull request, please give review guys. Not made it responsive will make all component lib first then go for responsiveness.

### CODE REVIEW

**Review by Asuraking1n — COMMENTED** [review]
Looks good...just not responsive for mobile

**Comment by atharvabhanage02** [comment]
Can include comments wherever necessary otherwise everything looks clean, good to merge

**Comment by TusharJade** [comment]
> Looks good...just not responsive for mobile
> 

yahh going to make it responsive after making all comppments

**Comment by TusharJade** [comment]
> Can include comments wherever necessary otherwise everything looks clean, good to merge

Thanks bro, I added comment in docs.css and for other files I dont think I needed to add comments right or any suggetion?

**Comment by TusharJade** [comment]
> Looks good...just not responsive for mobile

made it responsive for mobile have a look

**Comment by atharvabhanage02** [comment]
Everything else looks Great 👍

**Comment by TusharJade** [comment]
> Everything else looks Great 👍

Thanks bhava🙌

**Pull request merged**
